### ISSUE TITLE
Fragment Recyclerview

### ISSUE THREAD

**Issue by umair-b** [MOLOFP/wits-overflow#4]
The Fragment Recyclerview is overlapping the toolbar of the Main Activity.

**Comment by umair-b** [comment]
Temporary fix provided. Please search for a better solution, or close the issue if there is no better solution.

**Comment by SNR99** [comment]
I don't see the problem you highlighting,  everything seems/ looks fine the Recyclerview and the toolbar behave the way they should, please provide a screenshot of the problem
